project:
  type: website
  output-dir: docs
  
freeze: true

website:
  title: "Austin R. Brown, Ph.D."
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: teaching/index.qmd
        text: Teaching
        
    right:
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:abrow708@kennesaw.edu"
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/draustinrbrown/
        rel: me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

